### PR TITLE
FIX: MopsExceptions translated to german

### LINKED ISSUE #178: MopsExceptions in German?
Shall we use for our MopsException German messages as they will be printed in the UI?

Kind of silly writing this issue in English :wink: :rofl:

### PR DESCRIPTION
**Pull request by KaFe23**
closes #178

### CODE REVIEW

File: src/main/java/mops/businesslogic/DirectoryServiceImpl.java [hunk 1]
```diff
@@ -226,7 +226,7 @@ public Directory getDirectory(long dirId) throws MopsException {
         try {
             return fetchDirectory(dirId);
         } catch (NoSuchElementException e) {
-            throw new MopsException("Error on retrieving Directory", e);
+            throw new MopsException("Fehler beim abrufen des Verzeichnis", e);
```
Comment (iTitus) [inline src/main/java/mops/businesslogic/DirectoryServiceImpl.java]:
```suggestion
            throw new MopsException("Fehler beim Abrufen des Verzeichnis", e);
```

Comment (kosch104) [inline src/main/java/mops/businesslogic/DirectoryServiceImpl.java]:
```suggestion
            throw new MopsException("Fehler beim Abrufen des Verzeichnis", e);
```

Sprich Deutsch

File: src/main/java/mops/businesslogic/FileServiceImpl.java [hunk 2]
```diff
@@ -95,7 +95,7 @@ public FileContainer getFile(Account account, long fileId) throws MopsException
                     fileId,
                     e.getMessage()
             );
-            throw new FileNotFoundException("File with ID " + fileId + " not found", e);
+            throw new FileNotFoundException("Datei mit ID " + fileId + " wurde nicht gefunden", e);
```
Comment (iTitus) [inline src/main/java/mops/businesslogic/FileServiceImpl.java]: use String.format here instead of string concat

File: src/main/java/mops/businesslogic/RoleServiceImpl.java [hunk 3]
```diff
@@ -46,9 +46,10 @@ public void checkWritePermission(Account account, Directory directory) throws Mo
             log.error("The user '{}' tried to write in '{}' where they have no write permissions.",
                     account.getName(),
                     directory.getName());
-            throw new WriteAccessPermissionException(String.format("The user %s doesn't have write access in {}.",
-                    account.getName(),
-                    directory.getName()));
+            throw new WriteAccessPermissionException(
+                    String.format("Der Benutzer %s hat keine Schreibberechtigungen auf %s.",
```
Comment (iTitus) [inline src/main/java/mops/businesslogic/RoleServiceImpl.java]:
```suggestion
                    String.format("Der Benutzer %s hat keine Schreibberechtigungen in %s.",
```

File: src/main/java/mops/businesslogic/RoleServiceImpl.java [hunk 4]
```diff
@@ -68,9 +69,10 @@ public void checkReadPermission(Account account, Directory directory) throws Mop
             log.error("The user '{}' tried to read in '{}' where they have no read permissions.",
                     account.getName(),
                     directory.getName());
-            throw new ReadAccessPermissionException(String.format("The user %s doesn't have read access in %s.",
-                    account.getName(),
-                    directory.getName()));
+            throw new ReadAccessPermissionException(
+                    String.format("Der Benutzer %s hat keine Leseberechtigungen auf %s.",
```
Comment (iTitus) [inline src/main/java/mops/businesslogic/RoleServiceImpl.java]:
```suggestion
                    String.format("Der Benutzer %s hat keine Leseberechtigungen in %s.",
```

File: src/main/java/mops/businesslogic/RoleServiceImpl.java [hunk 5]
```diff
@@ -92,9 +94,10 @@ public void checkDeletePermission(Account account, Directory directory) throws M
             log.error("The user '{}' tried to delete in '{}' where they have no delete permissions.",
                     account.getName(),
                     directory.getName());
-            throw new DeleteAccessPermissionException(String.format("The user %s doesn't have delete access in %s.",
-                    account.getName(),
-                    directory.getName()));
+            throw new DeleteAccessPermissionException(
+                    String.format("Der Benutzer %s hat keine Löschberechtigungen %s.",
```
Comment (iTitus) [inline src/main/java/mops/businesslogic/RoleServiceImpl.java]:
```suggestion
                    String.format("Der Benutzer %s hat keine Löschberechtigungen in %s.",
```

File: src/main/java/mops/businesslogic/FileServiceImpl.java [hunk 6]
```diff
@@ -105,7 +105,7 @@ public FileContainer getFile(Account account, long fileId) throws MopsException
                     account.getName(),
                     fileId
             );
-            throw new ReadAccessPermissionException("No read permission");
+            throw new ReadAccessPermissionException("Keine Schreibberechtigung");
```
Comment (ali3654) [inline src/main/java/mops/businesslogic/FileServiceImpl.java]: "Keine Leseberechtigung"

File: src/main/java/mops/businesslogic/DirectoryServiceImpl.java (hunk 1 above)
Comment (Thabb) [inline src/main/java/mops/businesslogic/DirectoryServiceImpl.java]:
```suggestion
            throw new MopsException("Fehler beim Abrufen des Verzeichnisses", e);
```
Grammar, bitch
