### PR TITLE
FIX: get or create root

### LINKED ISSUE #196: Change create directory to also get it when available
https://github.com/hhu-propra2/abschlussprojekt-mopse/blob/d0958c119648265a54c32517d0c0cf50e0aa59b4/src/main/java/mops/businesslogic/DirectoryServiceImpl.java#L113

### PR DESCRIPTION
**Pull request by kosch104**
closes #196

### CODE REVIEW

File: src/main/java/mops/businesslogic/DirectoryServiceImpl.java [hunk 1]
```diff
@@ -108,10 +108,13 @@ public UserPermission getPermissionsOfUser(Account account, long dirId) throws M
...
-        roleService.checkIfRole(account, groupId, ADMIN);
+    @SuppressWarnings({ "PMD.LawOfDemeter", "PMD.OnlyOneReturn" })
+    public Directory getOrCreateRootFolder(long groupId) throws MopsException {
+        Optional<Directory> optionalDirectory = directoryRepository.getRootFolder(groupId);
+        if (optionalDirectory.isPresent()) {
+            return optionalDirectory.get();
+        }
+
         Set<String> roleNames = permissionService.fetchRolesInGroup(groupId);
         DirectoryPermissions rootPermissions = createDefaultPermissions(roleNames);
```
Comment (iTitus) [inline src/main/java/mops/businesslogic/DirectoryServiceImpl.java]: can you check here if roleNames is NOT empty and fail with an exception otherwise?

Comment (kosch104) [reply src/main/java/mops/businesslogic/DirectoryServiceImpl.java]: Where exactly check? Before line 114, or between 116 and 118? Or before 119?

Comment (iTitus) [reply src/main/java/mops/businesslogic/DirectoryServiceImpl.java]: where it makes sense. everyone may get the root directory, but it may only be created if the group exists
